---
version: "3.7"

# This Docker composition file is used to build and test the container

secrets:
  quote_txt:
    file: ./src/secrets/quote.txt

services:
  http-redirector:
    # Run the container normally
    build:
      # VERSION must be specified on the command line:
      # e.g., --build-arg VERSION=0.0.1
      context: .
      dockerfile: Dockerfile
    image: cisagov/apache2:latest
    container_name: apache
    init: true
    restart: "no"
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./src/:/var/www/html
      - ./src/config/apache2.conf:/etc/apache2/apache2.conf
      - ./src/config/000-default.conf:/etc/apache2/sites-available/000-default.conf
